### We're going to make a copy of the preconfigured AMI
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
    - files/secrets.yml
  tasks:
    - name: Basic provisioning of an AMI from our Instance
      ec2_ami:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        instance_id: "{{ inst_id }}"
        wait: no
        name: nodeAppImage
        tags:
          Name: NodeAppImage
          Service: NodeAppImg

      register: instance

    - name: Display the results
      debug: var=instance
