---
- hosts: localhost
  connection: local
  remote_user: test
  become: yes
  gather_facts: no
  vars_files:
  - files/secrets.yml
  tasks:
  ### Create Amazon EC2 key pair
  - name: Amazon EC2 | Create Key Pair
    ec2_key:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      name: "{{ ssh_keyname }}"
      region: "{{ aws_region }}"
    with_file: "{{ key_location }}"
  ### Create EC2 Instance
  - name: Basic provisioning of an EC2 instance
    ec2:
      aws_access_key: "{{ aws_id }}"
      aws_secret_key: "{{ aws_key }}"
      region: "{{ aws_region }}"
      image: "{{ ubuntu_ami }}"
      instance_type: "{{ free_instance }}"
      group_id: "{{ secgroup_id }}"
      key_name: "{{ ssh_keyname }}"
      wait: no
      instance_tags:
        Name: "{{ app_name }}"
      exact_count: 1
      count_tag: Name
    register: ec2info

  - name: Print the results
    debug: var=ec2info
### try installing some basic packages
